name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
    - run: yarn
    - run: CI= yarn run build

    - name: Deploy to Skynet
      uses: kwypchlo/deploy-to-skynet-action@v1.2.0
      with:
        upload-dir: build
        github-token: ${{ secrets.GITHUB_TOKEN }}